CREATE TABLE IF NOT EXISTS public.items (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT,
	is_active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.variants (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	category VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	is_active BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.item_variants (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	item_id BIGINT NOT NULL,
	code VARCHAR(255) NOT NULL,
	price DECIMAL,
	stock INT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT fk_item_variants_items
	  FOREIGN KEY (item_id)
	  REFERENCES items (id)
	  ON DELETE CASCADE,
 	CONSTRAINT uk_item_variants_code
     UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.item_variant_maps (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	item_variant_id BIGINT NOT NULL,
	variant_id BIGINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE,
	CONSTRAINT fk_item_variant_maps_item_variants
	  FOREIGN KEY (item_variant_id)
	  REFERENCES item_variants (id)
	  ON DELETE CASCADE,
	CONSTRAINT fk_item_variant_maps_variants
	  FOREIGN KEY (variant_id)
	  REFERENCES variants (id)
	  ON DELETE CASCADE
);